/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelgskidskolaRouteImport } from './routes/helgskidskola'
import { Route as HostsasongRouteImport } from './routes/hostsasong'
import { Route as KalenderRouteImport } from './routes/kalender'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as PrivatlektionRouteImport } from './routes/privatlektion'
import { Route as RookieSeriesRouteImport } from './routes/rookie-series'
import { Route as SkidklubbRouteImport } from './routes/skidklubb'
import { Route as SponsorRouteImport } from './routes/sponsor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelgskidskolaRoute = HelgskidskolaRouteImport.update({
  id: '/helgskidskola',
  path: '/helgskidskola',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsasongRoute = HostsasongRouteImport.update({
  id: '/hostsasong',
  path: '/hostsasong',
  getParentRoute: () => rootRouteImport,
} as any)
const KalenderRoute = KalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlektionRoute = PrivatlektionRouteImport.update({
  id: '/privatlektion',
  path: '/privatlektion',
  getParentRoute: () => rootRouteImport,
} as any)
const RookieSeriesRoute = RookieSeriesRouteImport.update({
  id: '/rookie-series',
  path: '/rookie-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SkidklubbRoute = SkidklubbRouteImport.update({
  id: '/skidklubb',
  path: '/skidklubb',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/helgskidskola': typeof HelgskidskolaRoute
  '/hostsasong': typeof HostsasongRoute
  '/kalender': typeof KalenderRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/privatlektion': typeof PrivatlektionRoute
  '/rookie-series': typeof RookieSeriesRoute
  '/skidklubb': typeof SkidklubbRoute
  '/sponsor': typeof SponsorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/helgskidskola': typeof HelgskidskolaRoute
  '/hostsasong': typeof HostsasongRoute
  '/kalender': typeof KalenderRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/privatlektion': typeof PrivatlektionRoute
  '/rookie-series': typeof RookieSeriesRoute
  '/skidklubb': typeof SkidklubbRoute
  '/sponsor': typeof SponsorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/helgskidskola': typeof HelgskidskolaRoute
  '/hostsasong': typeof HostsasongRoute
  '/kalender': typeof KalenderRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/privatlektion': typeof PrivatlektionRoute
  '/rookie-series': typeof RookieSeriesRoute
  '/skidklubb': typeof SkidklubbRoute
  '/sponsor': typeof SponsorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/helgskidskola'
    | '/hostsasong'
    | '/kalender'
    | '/kontakt'
    | '/om-oss'
    | '/privatlektion'
    | '/rookie-series'
    | '/skidklubb'
    | '/sponsor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/helgskidskola'
    | '/hostsasong'
    | '/kalender'
    | '/kontakt'
    | '/om-oss'
    | '/privatlektion'
    | '/rookie-series'
    | '/skidklubb'
    | '/sponsor'
  id:
    | '__root__'
    | '/'
    | '/helgskidskola'
    | '/hostsasong'
    | '/kalender'
    | '/kontakt'
    | '/om-oss'
    | '/privatlektion'
    | '/rookie-series'
    | '/skidklubb'
    | '/sponsor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelgskidskolaRoute: typeof HelgskidskolaRoute
  HostsasongRoute: typeof HostsasongRoute
  KalenderRoute: typeof KalenderRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  PrivatlektionRoute: typeof PrivatlektionRoute
  RookieSeriesRoute: typeof RookieSeriesRoute
  SkidklubbRoute: typeof SkidklubbRoute
  SponsorRoute: typeof SponsorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helgskidskola': {
      id: '/helgskidskola'
      path: '/helgskidskola'
      fullPath: '/helgskidskola'
      preLoaderRoute: typeof HelgskidskolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostsasong': {
      id: '/hostsasong'
      path: '/hostsasong'
      fullPath: '/hostsasong'
      preLoaderRoute: typeof HostsasongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalender': {
      id: '/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof KalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatlektion': {
      id: '/privatlektion'
      path: '/privatlektion'
      fullPath: '/privatlektion'
      preLoaderRoute: typeof PrivatlektionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rookie-series': {
      id: '/rookie-series'
      path: '/rookie-series'
      fullPath: '/rookie-series'
      preLoaderRoute: typeof RookieSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skidklubb': {
      id: '/skidklubb'
      path: '/skidklubb'
      fullPath: '/skidklubb'
      preLoaderRoute: typeof SkidklubbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelgskidskolaRoute: HelgskidskolaRoute,
  HostsasongRoute: HostsasongRoute,
  KalenderRoute: KalenderRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  PrivatlektionRoute: PrivatlektionRoute,
  RookieSeriesRoute: RookieSeriesRoute,
  SkidklubbRoute: SkidklubbRoute,
  SponsorRoute: SponsorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
